# 网站设置
title: "张志超的个人博客"
description: "分享技术、思考和生活的地方"
baseurl: ""
url: "https://diablozzc.github.io"

# 作者信息
author:
  name: "张志超"
  email: "your-email@example.com"
  github: "diablozzc"
  bio: "热爱技术的开发者"

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 集合
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# 默认值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "张志超"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# 时区
timezone: Asia/Shanghai

# 语言
lang: zh-CN

# 社交媒体链接
social_links:
  github: "https://github.com/diablozzc"
  email: "mailto:your-email@example.com"

# 搜索设置
search: true

# 主题色彩
theme_color: "#2563eb" 